#!/bin/bash

source ~/anaconda3/etc/profile.d/conda.sh  # Ensure conda is available
conda activate ppt

METHOD=$1
QUERY=$2

python -m graphrag.query \
--root ~/digital_human_group/graphrag \
--method "$METHOD" \
"$QUERY"
